2025-05-25 05:15:50,794 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:54,884 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:54,886 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:15:58,973 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:15:58,975 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:16:03,045 ERROR: Unhandled Error: (2002, "Can't connect to server on 'localhost' (10061)") [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:53]
2025-05-25 05:16:03,049 ERROR: Traceback (most recent call last):
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\INFO\app.py", line 183, in before_request
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 94, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\flask_mysqldb\__init__.py", line 81, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Learn Flask\INFO_FINAL\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (2002, "Can't connect to server on 'localhost' (10061)")
 [in D:\Learn Flask\INFO_FINAL\INFO\error_handlers.py:54]
2025-05-25 05:17:36,050 INFO: Action: login_manual_password_success, User: Ali, Details: Password verified for user Ali. Proceeding to 2FA. [in D:\Learn Flask\INFO_FINAL\INFO\app.py:805]
2025-05-25 15:02:51,813 ERROR: Error in registration process: 'NoneType' object has no attribute 'cursor' [in C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py:286]
2025-05-25 15:02:51,820 ERROR: Error details: Traceback (most recent call last):
  File "C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py", line 251, in register
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
 [in C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py:287]
2025-05-25 15:04:08,097 ERROR: Unhandled Error: 'NoneType' object has no attribute 'cursor' [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:53]
2025-05-25 15:04:08,102 ERROR: Traceback (most recent call last):
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py", line 355, in login
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
 [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:54]
2025-05-25 15:05:49,201 ERROR: Unhandled Error: 'NoneType' object has no attribute 'cursor' [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:53]
2025-05-25 15:05:49,294 ERROR: Traceback (most recent call last):
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py", line 355, in login
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
 [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:54]
2025-05-25 15:06:32,327 ERROR: Unhandled Error: 'NoneType' object has no attribute 'cursor' [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:53]
2025-05-25 15:06:32,338 ERROR: Traceback (most recent call last):
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maraw\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\maraw\Downloads\Info_final\INFO\vulnerable_app.py", line 355, in login
    cur = mysql.connection.cursor()
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'cursor'
 [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:54]
2025-05-25 15:16:25,961 ERROR: Unhandled Error: 'NoneType' object has no attribute 'cursor' [in C:\Users\maraw\Downloads\Info_final\INFO\error_handlers.py:53]
